/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Saputra
 */
public class AplikasiPerhitunganDiskon extends javax.swing.JFrame {

    // Deklarasi variabel untuk menyimpan harga dan diskon
    private double harga = 0.0;
    private double diskon = 10.0; // Inisialisasi nilai default sesuai pilihan pertama (10%)
    private double hasil = 0.0;
    private static final double DISKON_MAKSIMAL = 90.0;
    private StringBuilder riwayatPerhitungan = new StringBuilder();

    /** Creates new form AplikasiPerhitunganDiskon */
    public AplikasiPerhitunganDiskon() {
        initComponents();
        // Inisialisasi nilai diskon saat aplikasi pertama kali dibuka
        String selectedDiskon = (String) cbDiskon.getSelectedItem();
        diskon = Double.parseDouble(selectedDiskon.replace("%", ""));
        setupComponents();
    }

    private void setupComponents() {
        // Setup JSlider
        jSlider1.setMinimum(0);
        jSlider1.setMaximum(90);
        jSlider1.setValue(10);
        jSlider1.setPaintTicks(true);
        jSlider1.setPaintLabels(true);
        jSlider1.setMajorTickSpacing(10);
        
        // Setup TextArea untuk riwayat
        jTextArea1.setEditable(false);
        
        // Tambahkan listener untuk slider
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderStateChanged(evt);
            }
        });
    }

    private void sliderStateChanged(javax.swing.event.ChangeEvent evt) {
        // Update ComboBox saat slider berubah
        int sliderValue = jSlider1.getValue();
        updateDiskonValue(sliderValue);
        // Cari nilai terdekat di ComboBox
        String closestValue = findClosestComboBoxValue(sliderValue);
        cbDiskon.setSelectedItem(closestValue);
    }

    private void updateDiskonValue(double newDiskon) {
        // Validasi diskon maksimal
        diskon = Math.min(newDiskon, DISKON_MAKSIMAL);
    }

    private String findClosestComboBoxValue(int value) {
        String[] items = {"10%", "20%", "50%", "70%"};
        int closest = 10;
        for (String item : items) {
            int itemValue = Integer.parseInt(item.replace("%", ""));
            if (Math.abs(value - itemValue) < Math.abs(value - closest)) {
                closest = itemValue;
            }
        }
        return closest + "%";
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfHarga = new javax.swing.JTextField();
        cbDiskon = new javax.swing.JComboBox<>();
        btnHitung = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tfHasil = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        tfKupon = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Diskon Diskonnn!!!", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 14))); // NOI18N
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Masukan Harga");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 5);
        jPanel1.add(jLabel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 2, 5, 60);
        jPanel1.add(tfHarga, gridBagConstraints);

        cbDiskon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10%", "20%", "50%", "70%" }));
        cbDiskon.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbDiskonItemStateChanged(evt);
            }
        });
        cbDiskon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDiskonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 22;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(cbDiskon, gridBagConstraints);

        btnHitung.setBackground(new java.awt.Color(204, 255, 204));
        btnHitung.setText("Hitung!");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(btnHitung, gridBagConstraints);

        jLabel2.setText("Masukan Diskon");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel2, gridBagConstraints);

        tfHasil.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 40;
        jPanel1.add(tfHasil, gridBagConstraints);

        jLabel3.setText("Hraga Diskon");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 1, 0, 0);
        jPanel1.add(jLabel3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        jPanel1.add(jSlider1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel1.add(tfKupon, gridBagConstraints);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(jScrollPane1, gridBagConstraints);

        jLabel4.setText("Masukan Kupon Diskon");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        jPanel1.add(jLabel4, gridBagConstraints);

        jLabel5.setText("Riwayat Diskon");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        jPanel1.add(jLabel5, gridBagConstraints);

        jLabel6.setText("Kode kupon: K10S");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_START;
        jPanel1.add(jLabel6, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        try {
            // Mengambil input harga dari text field
            String hargaInput = tfHarga.getText().trim(); // Tambahkan trim() untuk membersihkan spasi
            
            // Validasi input tidak boleh kosong
            if (hargaInput.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "Harga tidak boleh kosong!",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            harga = Double.parseDouble(hargaInput);
            
            // Validasi harga tidak boleh negatif
            if (harga < 0) {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "Harga tidak boleh negatif!",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
                tfHarga.setText("");
                return;
            }
            
            // Proses kupon terlebih dahulu
            String kupon = tfKupon.getText().trim().toUpperCase();
            double diskonTambahan = hitungDiskonKupon(kupon);
            String statusKupon;
            
            if (kupon.isEmpty()) {
                statusKupon = "Tanpa Kupon";
            } else if (diskonTambahan > 0) {
                statusKupon = "Kupon Valid";
            } else {
                statusKupon = "Kupon Tidak Valid";
            }
            
            // Hitung total diskon sekali saja
            double totalDiskon = Math.min(diskon + diskonTambahan, DISKON_MAKSIMAL);
            double jumlahDiskon = harga * (totalDiskon / 100);
            hasil = harga - jumlahDiskon;
            
            // Format hasil
            java.text.NumberFormat currencyFormat = java.text.NumberFormat.getInstance(new java.util.Locale("id", "ID"));
            currencyFormat.setMinimumFractionDigits(2);
            currencyFormat.setMaximumFractionDigits(2);
            
            String formattedHasil = "Rp " + currencyFormat.format(hasil);
            tfHasil.setText(formattedHasil);
            
            // Tampilkan info penghematan
            String pesanPenghematan = "Anda hemat: Rp " + currencyFormat.format(jumlahDiskon);
            javax.swing.JOptionPane.showMessageDialog(this, pesanPenghematan, "Info Penghematan", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            
            // Update riwayat
            String riwayat = String.format("Harga: Rp %s | Diskon: %.0f%% | Kupon: %s (%s) | Hasil: %s\n",
                currencyFormat.format(harga), totalDiskon, kupon.isEmpty() ? "-" : kupon, statusKupon, formattedHasil);
            riwayatPerhitungan.insert(0, riwayat);
            jTextArea1.setText(riwayatPerhitungan.toString());
            
        } catch (NumberFormatException e) {
            // Menangani kesalahan input
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Masukkan harga yang valid!", 
                "Error", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
            tfHarga.setText("");
            tfHasil.setText("");
        }
    }//GEN-LAST:event_btnHitungActionPerformed

    private void cbDiskonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbDiskonItemStateChanged
        // Mengupdate nilai diskon ketika pilihan berubah
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            String selectedDiskon = (String) cbDiskon.getSelectedItem();
            // Mengambil nilai numerik dari string diskon (menghapus karakter %)
            diskon = Double.parseDouble(selectedDiskon.replace("%", ""));
        }
    }//GEN-LAST:event_cbDiskonItemStateChanged

    private void cbDiskonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDiskonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbDiskonActionPerformed

    private double hitungDiskonKupon(String kupon) {
        // Hanya menerima kupon "K10S" untuk diskon 10%
        if (kupon.equals("K10S")) {
            return 10.0;
        }
        return 0.0;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplikasiPerhitunganDiskon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplikasiPerhitunganDiskon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplikasiPerhitunganDiskon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplikasiPerhitunganDiskon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplikasiPerhitunganDiskon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHitung;
    private javax.swing.JComboBox<String> cbDiskon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField tfHarga;
    private javax.swing.JTextField tfHasil;
    private javax.swing.JTextField tfKupon;
    // End of variables declaration//GEN-END:variables

}
