/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Saputra
 */
public class AplikasiPerhitunganDiskon extends javax.swing.JFrame {

    // Deklarasi variabel untuk menyimpan harga dan diskon
    private double harga = 0.0;
    private double diskon = 10.0; // Inisialisasi nilai default sesuai pilihan pertama (10%)
    private double hasil = 0.0;

    /** Creates new form AplikasiPerhitunganDiskon */
    public AplikasiPerhitunganDiskon() {
        initComponents();
        // Inisialisasi nilai diskon saat aplikasi pertama kali dibuka
        String selectedDiskon = (String) cbDiskon.getSelectedItem();
        diskon = Double.parseDouble(selectedDiskon.replace("%", ""));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfHarga = new javax.swing.JTextField();
        cbDiskon = new javax.swing.JComboBox<>();
        btnHitung = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tfHasil = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Diskon Diskonnn!!!", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 14))); // NOI18N
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Masukan Harga");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 5);
        jPanel1.add(jLabel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(tfHarga, gridBagConstraints);

        cbDiskon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10%", "20%", "50%", "90%" }));
        cbDiskon.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbDiskonItemStateChanged(evt);
            }
        });
        cbDiskon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDiskonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(cbDiskon, gridBagConstraints);

        btnHitung.setText("Hitung!");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(btnHitung, gridBagConstraints);

        jLabel2.setText("Masukan Diskon");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel2, gridBagConstraints);

        tfHasil.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 40;
        jPanel1.add(tfHasil, gridBagConstraints);

        jLabel3.setText("Hraga Diskon");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 1, 0, 0);
        jPanel1.add(jLabel3, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 684, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        try {
            // Mengambil input harga dari text field
            String hargaInput = tfHarga.getText().trim(); // Tambahkan trim() untuk membersihkan spasi
            
            // Validasi input tidak boleh kosong
            if (hargaInput.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "Harga tidak boleh kosong!",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            harga = Double.parseDouble(hargaInput);
            
            // Validasi harga tidak boleh negatif
            if (harga < 0) {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "Harga tidak boleh negatif!",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
                tfHarga.setText("");
                return;
            }
            
            // Menghitung diskon berdasarkan persentase yang dipilih
            double diskonPersen = diskon;
            double jumlahDiskon = harga * (diskonPersen / 100);
            hasil = harga - jumlahDiskon;
            
            // Membuat format currency dengan pemisah ribuan
            java.text.NumberFormat currencyFormat = java.text.NumberFormat.getInstance(new java.util.Locale("id", "ID"));
            currencyFormat.setMinimumFractionDigits(2);
            currencyFormat.setMaximumFractionDigits(2);
            
            // Menampilkan hasil perhitungan dengan format currency
            String formattedHasil = "Rp " + currencyFormat.format(hasil);
            tfHasil.setText(formattedHasil);
            
            // Menampilkan informasi penghematan dengan format currency
            String pesanPenghematan = "Anda hemat: Rp " + currencyFormat.format(jumlahDiskon);
            javax.swing.JOptionPane.showMessageDialog(this, pesanPenghematan, "Info Penghematan", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            
        } catch (NumberFormatException e) {
            // Menangani kesalahan input
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Masukkan harga yang valid!", 
                "Error", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
            tfHarga.setText("");
            tfHasil.setText("");
        }
    }//GEN-LAST:event_btnHitungActionPerformed

    private void cbDiskonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbDiskonItemStateChanged
        // Mengupdate nilai diskon ketika pilihan berubah
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            String selectedDiskon = (String) cbDiskon.getSelectedItem();
            // Mengambil nilai numerik dari string diskon (menghapus karakter %)
            diskon = Double.parseDouble(selectedDiskon.replace("%", ""));
        }
    }//GEN-LAST:event_cbDiskonItemStateChanged

    private void cbDiskonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDiskonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbDiskonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplikasiPerhitunganDiskon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplikasiPerhitunganDiskon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplikasiPerhitunganDiskon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplikasiPerhitunganDiskon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplikasiPerhitunganDiskon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHitung;
    private javax.swing.JComboBox<String> cbDiskon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tfHarga;
    private javax.swing.JTextField tfHasil;
    // End of variables declaration//GEN-END:variables

}
